language: go
sudo: false

env:
  - TESTING_LOGGER_LEVEL=fatal

matrix:
  include:
    - go: 1.9
    - go: tip
  allow_failures:
    - go: tip

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go vet $(go list ./...)
  - go test -v -race $(go list ./...)
