language: go
sudo: false

env:
  - TESTING_LOGGER_LEVEL=fatal

matrix:
  include:
    - go: 1.7
    - go: tip
  allow_failures:
    - go: tip

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race $(go list ./... | grep -v /vendor/)
